ALTER TABLE "UserDetails"
    ADD COLUMN IF NOT EXISTS "CurrentGoal"      SMALLINT     NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS "TargetWeightKg"   DECIMAL(5,2) NULL,
    ADD COLUMN IF NOT EXISTS "TargetWeightLbs"  DECIMAL(5,2) NULL;