ALTER TABLE "Users" ALTER COLUMN "Id" DROP IDENTITY IF EXISTS;
ALTER TABLE "Users" DROP CONSTRAINT IF EXISTS "Users_pkey" CASCADE;

ALTER TABLE "Users" 
    ALTER COLUMN "Id" TYPE UUID USING gen_random_uuid();

ALTER TABLE "Users" ALTER COLUMN "Id" SET DEFAULT gen_random_uuid();
ALTER TABLE "Users" ADD PRIMARY KEY ("Id");

DROP INDEX IF EXISTS "User_Id";
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email" ON "Users" ("Email");